<?php

namespace DoctrineORMModule\Proxy\__CG__\Cms\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cms extends \Cms\Entity\Cms implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'titulo', 'texto', 'metaDescricao', 'metaPalavrasChave', 'fixa', 'id', 'cliente_id', 'criacao', 'alteracao', 'visivel');
        }

        return array('__isInitialized__', 'titulo', 'texto', 'metaDescricao', 'metaPalavrasChave', 'fixa', 'id', 'cliente_id', 'criacao', 'alteracao', 'visivel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cms $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexto($texto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexto', array($texto));

        return parent::setTexto($texto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTexto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexto', array());

        return parent::getTexto();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaDescricao($metaDescricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaDescricao', array($metaDescricao));

        return parent::setMetaDescricao($metaDescricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDescricao', array());

        return parent::getMetaDescricao();
    }
    
    /**
     * {@inheritDoc}
     */
    public function setMetaPalavrasChave($metaPalavrasChave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaPalavrasChave', array($metaPalavrasChave));

        return parent::setMetaPalavrasChave($metaPalavrasChave);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaPalavrasChave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaPalavrasChave', array());

        return parent::getMetaPalavrasChave();
    }
    
    /**
     * {@inheritDoc}
     */
    public function setFixa($fixa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFixa', array($fixa));

        return parent::setFixa($fixa);
    }

    /**
     * {@inheritDoc}
     */
    public function isFixa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFixa', array());

        return parent::isFixa();
    }

    /**
     * {@inheritDoc}
     */
    public function setClienteId($clienteId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClienteId', array($clienteId));

        return parent::setClienteId($clienteId);
    }

    /**
     * {@inheritDoc}
     */
    public function getClienteId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClienteId', array());

        return parent::getClienteId();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function defineTimestamps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'defineTimestamps', array());

        return parent::defineTimestamps();
    }

    /**
     * {@inheritDoc}
     */
    public function log()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'log', array());

        return parent::log();
    }

    /**
     * {@inheritDoc}
     */
    public function setCriacao($criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCriacao', array($criacao));

        return parent::setCriacao($criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCriacao($formatted = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriacao', array($formatted));

        return parent::getCriacao($formatted);
    }

    /**
     * {@inheritDoc}
     */
    public function setAlteracao($alteracao)
    {
 
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlteracao', array($alteracao));

        return parent::setAlteracao($alteracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlteracao($formatted = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlteracao', array($formatted));

        return parent::getAlteracao($formatted);
    }

    /**
     * {@inheritDoc}
     */
    public function setVisivel($visivel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisivel', array($visivel));

        return parent::setVisivel($visivel);
    }

    /**
     * {@inheritDoc}
     */
    public function isVisivel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVisivel', array());

        return parent::isVisivel();
    }

}
