<?php

namespace DoctrineORMModule\Proxy\__CG__\Usuarios\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \Usuarios\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'nome', 'email', 'senha', 'perfil', 'id', 'cliente_id', 'criacao', 'alteracao', 'visivel');
        }

        return array('__isInitialized__', 'nome', 'email', 'senha', 'perfil', 'id', 'cliente_id', 'criacao', 'alteracao', 'visivel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerfil($perfil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerfil', array($perfil));

        return parent::setPerfil($perfil);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerfil', array());

        return parent::getPerfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setClienteId($clienteId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClienteId', array($clienteId));

        return parent::setClienteId($clienteId);
    }

    /**
     * {@inheritDoc}
     */
    public function getClienteId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClienteId', array());

        return parent::getClienteId();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function defineTimestamps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'defineTimestamps', array());

        return parent::defineTimestamps();
    }

    /**
     * {@inheritDoc}
     */
    public function log()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'log', array());

        return parent::log();
    }

    /**
     * {@inheritDoc}
     */
    public function setCriacao($criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCriacao', array($criacao));

        return parent::setCriacao($criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCriacao($formatted = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriacao', array($formatted));

        return parent::getCriacao($formatted);
    }

    /**
     * {@inheritDoc}
     */
    public function setAlteracao($alteracao)
    {
 
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlteracao', array($alteracao));

        return parent::setAlteracao($alteracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlteracao($formatted = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlteracao', array($formatted));

        return parent::getAlteracao($formatted);
    }

    /**
     * {@inheritDoc}
     */
    public function setVisivel($visivel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisivel', array($visivel));

        return parent::setVisivel($visivel);
    }

    /**
     * {@inheritDoc}
     */
    public function isVisivel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVisivel', array());

        return parent::isVisivel();
    }

}
